@startuml
class Estudiant {
    - dni : String
    - nom : String
    - cognoms : String
    - notaFinal : Double
    + Estudiant(dni, nom, cognoms, notaFinal)
    + getNotaFinal() : Double
    + toString() : String
}

class Professor {
    - nom : String
    - cognoms : String
    - formacio : String
    + Professor(nom, cognoms, formacio)
    + toString() : String
}

class Grup {
    - nom : String
    - llistaEstudiants : List<Estudiant>
    - tutor : Professor
    + Grup(nom, tutor)
    + afegirEstudiant(estudiant)
    + numAprovats() : Int
    + estudiantsAprovats() : List<Estudiant>
    + toString() : String
}

@enduml